
import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AppFooter from './components/app.footer'
import AppHeader from './components/app.header'
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>

      <body className={inter.className}>
        <AppHeader />
        <div style={{ minHeight: 'calc(100vh - 106px)' }}>
          {children}
        </div>
        <AppFooter />
        <ToastContainer
          position="bottom-center"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
      </body>

    </html>
  )
}
